### PR TITLE
Add missing TType 'Object' to parser. Fixes #616

### LINKED ISSUE #616: Represent type Object is not recognized.
While doing the example, I tried to explicitly state that two concepts should be represented by type 'object', but this seems not to be allowed. This seems inconsistent, because Object is the default type, right? Is this desired behavior?

Example fragment:
```adl
REPRESENT Date TYPE DATE
REPRESENT Name, Description TYPE ALPHANUMERIC
REPRESENT Person, Project TYPE OBJECT
```

### PR DESCRIPTION
**Pull request by Michiel-s**

### CODE REVIEW

**Comment by Michiel-s** [comment]
@hanjoosten 

Ad 1: Nope, no issue there. I've tested this.

```adl
CONTEXT Issue616
    CONCEPT A ""
    REPRESENT A TYPE OBJECT

    CONCEPT B ""
    CLASSIFY B ISA A
    REPRESENT B TYPE ALPHANUMERIC
ENDCONTEXT
```
output
```
Error at symbol () in file \Issue616.adl at line 4 : 5
  Concepts in the same typology must have the same TYPE.
The following concepts are in the same typology, but not all
of them have the same TYPE:
  - REPRESENT A TYPE OBJECT at Error at symbol () in file C:\dev\Ampersand\projects\Issues\Issue616.adl at line 4 : 5
  - REPRESENT B TYPE ALPHANUMERIC at Error at symbol () in file C:\dev\Ampersand\projects\Issues\Issue616.adl at line 8 : 5
```

Ad 2. Not sure what you expect of me here, but I'll wait for the result of travis to get a hint. I've only added a missing represent type, which was already supported and implemented elsewhere in the code.

**Comment by Michiel-s** [comment]
@hanjoosten, Ad 2, Never mind, I think that I know what to do, e.g. in src/Ampersand/Test/Parser/ArbitraryTree.hs.

I’ll look into this.

**Comment by hanjoosten** [comment]
Nice work!

**Comment by Michiel-s** [comment]
* I've added Object as allowed TType in src/Ampersand/Test/Parser/ArbitraryTree.hs.
* Furthermore I think no changes are required to the pretty printer, because the TType is already covered:
```haskell
instance Pretty TType where
    pretty = text . show
```
* Check's are passing.

**Pull request merged**
