### PR TITLE
Feature/devcontainer maintenance

### PR DESCRIPTION
**Pull request by hanjoosten**
This PR is about some maintenance with the devcontainer, and also to try out the new way of working with automatic forced formatting.

### CODE REVIEW

**Review by stefjoosten — APPROVED** [review]

**Comment by Michiel-s** [comment]
When checking the commits and changes of this PR I noticed that there is also a commit regarding stale issues and some refactoring. The PR nor the change log mentions anything of this. I think this is bad practice and we shouldn't allow this.

If I was requested to review I would have suggested to a) split the PR or b) update change log and PR description accordingly.

@stefjoosten Please pay attention to this when reviewing code.

**Comment by hanjoosten** [comment]
Sorry. I plead guilty. I should have mentioned the introduction of the stale-issues bot in the description of this PR.

**Comment by stefjoosten** [comment]
Nevertheless, thanks for mentioning this, @Michiel ***@***.***>.  I need this sort of feedback because I’m not nearly as professional in my behaviour as I want to be. So keep it up…
Stef

PS This is also meant to see what happens when I reply by mail.

Van: Han Joosten ***@***.***>
Beantwoorden - Aan: AmpersandTarski/Ampersand ***@***.***>
Datum: woensdag 1 december 2021 om 11:50
Aan: AmpersandTarski/Ampersand ***@***.***>
CC: ***@***.***" ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [AmpersandTarski/Ampersand] Feature/devcontainer maintenance (PR #1260)


Sorry. I plead guilty. I should have mentioned the introduction of the stale-issues bot in the description of this PR.

**Comment by hanjoosten** [comment]
@stefjoosten when you reply by mail, a lot of sh*t is added to your comment. Also, as you can see above, everyone now could unsubscribe you from this thread ! My advice: Do not use mail to respond to comments, but use the webinterface for that.

**Pull request merged**
