### PR TITLE
Feature/pre processor

### PR DESCRIPTION
**Pull request by bartMarinissen**
Fix a bug where the pre-processor changed line numbers by adding or removing empty lines.

Most notably, every normal include (without a '--#') would get an extra empty line. Moreover, an --# IF, -- # ELSE --# ENDIF and their variants would eat all empty lines in front of them.

### CODE REVIEW

**Comment by RieksJ** [comment]
@bartMarinissen: ik zie een hele hoop regels over het scherm heen denderen die beginnen met `LEX: CODELINE`. Dat lijkt me niet de bedoeling. Kun je dat verwijderen?

**Comment by hanjoosten** [comment]
There is a limitation of appveyor. Such a build is limited to 3600 seconds (one hour). This isn't sufficient for us currently. However, for you guys nothing to worry about.

**Comment by RieksJ** [comment]
@bartMarinissen de testfiles (in `ampersand-models\Preprocessor`) werken niet (meer). Daar had ik natuurlijk zelf al eerder achter moeten komen (leerpunt voor mij). Kun je dat fixen?

**Comment by bartMarinissen** [comment]
@hanjoosten The last commit should fix the errors. After that, I think these changes can be merged. If desired, I can first merge the development branch into this branch to deal with any merge conflicts.

**Comment by hanjoosten** [comment]
> @hanjoosten The last commit should fix the errors. After that, I think these changes can be merged. If desired, I can first merge the development branch into this branch to deal with any merge conflicts.

As you can see, Travis-CI still complains. As soon as Travis is happy, I will be too. And yes, feel free to update this branch with the latest from development. This is required to do the merge.

**Comment by bartMarinissen** [comment]
> As you can see, Travis-CI still complains. As soon as Travis is happy, I will be too. 

That makes sense. The reason Travis complains is that the test cases use a feature that is not yet implemented (disabling a flag that was previously disabled). Thus I suppose I first need to add in that feature.

**Pull request merged**
