### PR TITLE
1093 prototype dependency

### PR DESCRIPTION
**Pull request by Michiel-s**
See issue #1093

### CODE REVIEW

**Review by hanjoosten — APPROVED** [review]

**Comment by Michiel-s** [comment]
@hanjoosten I've added an TODO for you. Would you be so kind to help me out here.
I would love to understand how to do this in Haskell.
I mentioned you in https://github.com/AmpersandTarski/Ampersand/pull/1122/commits/f3527801c6ef3aaedc5be67d33b179c66669726e

**Comment by hanjoosten** [comment]
> @hanjoosten I've added an TODO for you. Would you be so kind to help me out here.
> I would love to understand how to do this in Haskell.
> I mentioned you in [f352780](https://github.com/AmpersandTarski/Ampersand/commit/f3527801c6ef3aaedc5be67d33b179c66669726e)

Michiel, It seems you'd like to have a side effect in a piece of pure code. It is by design that Haskell will make your life hard on such things.
The good news is that this gives you the opportunity to rethink what you want. I see a solution that is even better than what you would do in some other language. Let's have a pair-programming session about this.

**Review by hanjoosten — APPROVED** [review]
👍

**Comment by Michiel-s** [comment]
@hanjoosten can you check why the macOS build is failing because of missing library `salve`, while ubuntu build succeeds. This feature requires `salve` package, so that dependency is new.

**Comment by Michiel-s** [comment]
Hi @hanjoosten, as I wrote above the salve package is needed for the feature we are introducing here. I.e. the compiler checks if its output is compatible with the installed prototype framework.

In the prototype framework there'll be a text file containing semantic versioning constraints. The compiler parses this file and checks the constraints. That's why we need salve.

Nice that you fixed the issue. I do not understand why Ubuntu build passed and MacOS not, but let's discuss that some other time

**Pull request merged**
