### PR TITLE
Feature/ghc 9

### PR DESCRIPTION
**Pull request by hanjoosten**
Upgrade to use GHC 9.0.2 . 
The upgrade itself is ready, however I do not recommend tot switch to it right now, because the haskell-language-server doesn't currently support it out of the box. Let's wait for that to happen. (See https://github.com/haskell/vscode-haskell#supported-ghc-versions). Only merge this PR when GHC 9.0.2 is supported. 
The state of support can be monitored here: https://github.com/haskell/haskell-language-server/issues/297

### CODE REVIEW

**Comment by hanjoosten** [comment]
@Michiel-s , There has been an upgrade of the package that we use to generate Sql. The regressiontest shows that all sql generated for the validation is fine. This makes me confident that there is no issue with quotes. However, I have no (larger) models to test this. You might want to test this before we merge this into main.

**Comment by Michiel-s** [comment]
Hi @hanjoosten,

I just compiled my advanced application (you know which one) using the compiler with ghc-9 from this branch.
I compared the output with the output of compiler v4.6.2

For generics folder:
* database.sql (containing database structure queries) --> no delta
* concepts.json --> no delta
* conjuncts.json (contains SQL statements) --> no delta
* interfaces.json (contains SQL statements) --> no delta
* populations.json (containing grinded meta-data) --> no functional deltas, only different order in which population is mentioned. --> no issues here.
* relations.json --> no delta
* rules.json --> no delta
* views.json (contains SQL statements) --> no delta


So my conclusion, the output of the updated SQL generated package stays exactly the same.

**Review by Michiel-s — APPROVED** [review]

**Comment by Michiel-s** [comment]
Hi @hanjoosten, just asking: why close not merge?

**Comment by hanjoosten** [comment]
I deleted this, because it is stale. Not all packages we depend on are ready for ghc 9. I just cleaned this one up, in the future I will see if everything we depend on works well with ghc 9, and start from a fresh main.

**Pull request closed without merging**
