### PR TITLE
Pdf graphics

### PR DESCRIPTION
**Pull request by hanjoosten**
@RieksJ and @stefjoosten,

This fix generates vector graphics in the PDF document. (Thanks to Wolfram Kahn). Before I pull this branch into the master, I would like you both to confirm that this works on your window machines. Please let me know if it works/doesn't work. for you.

Han.

### CODE REVIEW

**Comment by hanjoosten** [comment]
@RieksJ @stefjoosten 
To test this, just produce any .adl model with -fl switch. It should contain graphics that look great when zoomed into that graphic....

**Comment by RieksJ** [comment]
First: very nice that the Wolfram suggests concrete improvements related to the LaTeX stuff! Perphaps would he have some suggestions to improve on the presentation of relation-algebra rules (the ‘math’) in fspecs? That certainly would be nice!

As for your question: it seems to work, except that several .pdf files are created in the directory from where the ampersand scripts are read rather than in the directory I’ve specified for storing the functional specification files.

This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

**Comment by RieksJ** [comment]
Hi Han, it does not go well. I get several errors (but am currently not in a position to do more work on this as I am abroad for the week). Let’s talk things over next week. Rieks
This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

**Comment by hanjoosten** [comment]
Ok. You might want to make sure that you have the latest version of pdflatex (=MikTex) installed, and also graphviz (2.38).
I had problems at first, because I was using an old version.

**Pull request merged**
