### PR TITLE
Feature/pre processor

### PR DESCRIPTION
**Pull request by RieksJ**
AFAIK, the preprocessor cannot be tested automatically. However, there is a [test script](https://github.com/AmpersandTarski/ampersand-models/tree/master/Preprocessor) that allows you to play around a little to see how/that it works. The preprocessor stuff has also been documented in the gitbook section on ampersand language.

### CODE REVIEW

**Comment by sjcjoosten** [comment]
> has also been documented in the gitbook section

Can you link me? It sounds like fun!

**Comment by RieksJ** [comment]
[Documentation of Ampersand](https://ampersandtarski.gitbook.io/documentation)
--> [The Language Ampersand(https://ampersandtarski.gitbook.io/documentation/the-language-ampersand](https://ampersandtarski.gitbook.io/documentation/the-language-ampersand)
--> [The Preprocessor](https://ampersandtarski.gitbook.io/documentation/the-language-ampersand/the-preprocessor).

Funny that nerds (me as well as others) have trouble finding the existing documentation...

**Comment by hanjoosten** [comment]
Isn't [ampersandtarski.github.io](http://ampersandtarski.github.io) practical as landing page?

**Comment by RieksJ** [comment]
No that is not practical. When I enter that url, I end up in "The Tools we use for Ampersand". Then, I have to read a paragraph or two to find a text (that I inserted only recently) that allows you to go to the ampersand documentation (which is something that to me is very confusing, and to newbies as well it seems)

**Comment by hanjoosten** [comment]
> No that is not practical. When I enter that url, I end up in "The Tools we use for Ampersand". Then, I have to read a paragraph or two to find a text (that I inserted only recently) that allows you to go to the ampersand documentation (which is something that to me is very confusing, and to newbies as well it seems)

I really do not see how you manage to get to "The tools we use for ampersand", by hitting above link. Could you explain what you do exactly?

**Pull request merged**
