### PR TITLE
No automatic populating of singletons issue 166

### PR DESCRIPTION
**Pull request by hanjoosten**
In fixing this bug, I also discoverd a bug in concs of a Rule. That has been fixed on the fly.

### CODE REVIEW

**Comment by hanjoosten** [comment]
This fix makes the generator much slower. For that reason, do not merge into master yet.

**Comment by hanjoosten** [comment]
Getting rid of the tracé even made things worse 😟

**Comment by sjcjoosten** [comment]
Excellent! Sounds like something to be fixed with strictness annotations. I'll look into it this weekend; is there a single .adl file which I can use to test the performance on?

**Comment by hanjoosten** [comment]
There are quite af few testscripts that you could use for this purpose. In the [log of sentinel](http://sentinel.tarski.nl/logs/Sentinel_2016-02-18_17.37.56__311_of_567__amp=no_automatic_populating_of_singletons_issue_166:5c4a4cd_mdl=master:dfb6228_sen=master:624ac2a.html) you could take any script that fails with the ````ampersand: Heap exhausted```` message. There were over 300 scripts like that. 

For instance ampersand-models/Simple/DeliverySimple.adl does the job, but there are zillions others too.

**Comment by sjcjoosten** [comment]
I guess it's more than just a memory problem: Issue191Test.adl is very small so it should not create any memory problems, looks more like an infinite loop to me

**Comment by hanjoosten** [comment]
True. The concs of the expression EDcD <dcl>  was missing. I'm fixing it now.

**Pull request merged**
